version: '3.6'

volumes:
    mydata: {}

services:
    fpm:
        build:
            args:
                PHP_EXTS: intl pdo_mysql
                APK_EXTRA: mariadb-connector-c mysql-client
    dbserver:
        image: mysql:${MYSQL_VERSION:-8.0}
        ports:
            - ${MYSQL_PORT:-3306}:${DB_PORT:-3306}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mydata:/var/lib/mysql
        networks:
            - default
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
